### ISSUE TITLE
in the doc, add a usage example

### ISSUE THREAD

**Issue by survivant** [jstat/jstat#185]
It would be nice to have a example of usage in the documentation.  For now we can check in the test-cases, but not everyone will go there.

Another reason, is to understand what we are trying to do.  An example.
I'm trying to find the rejection rejet for a CentralF test.  I validate the result with my statistics book.
ex : 
values from my book
F> F (0.025,50,50) = 1.75
F< F (0.975,50,50) = -0.57

but when I'm using the library : 
jStat.centralF.inv(0,025, 50, 50).toFixed(4)  I obtain this : 0.5708
jStat.centralF.inv(0.975, 50, 50).toFixed(4)  I obtain this : 1.7520

I this point, I don't understand why I'm not obtaining the same result as my book.

That's why I little usage description could have help.

**Comment by jamescgibson** [comment]
I'd be happy to add examples if you think it'd be useful - the docs certainly aren't perfect. 

One recurring issue, which I think is what you're experiencing here, is that there are altering conventions between books / disciplines on how to to idiomatically define the distributions. 

jStat generally follows the lead of R and Matlab. For example, R's `qf(p, df1, df2)` is formulated in such a way as to return the positive X value; in R, `qf(0.025, 50, 50) = 0.5707915`. 

If making this more explicit in the docs would be helpful, I'd be happy to tackle it... eventually, or otherwise, pull requests welcome.

In particular, I'm not sure what `F < F(0.975, 50, 50) = -0.57` is intended to mean. The F distribution is only defined on x in the range [0, infinity], so the inverse of the cumulative F distribution should always be positive.

**Comment by survivant** [comment]
I'll be happy to help.  I'll finish stuying for my exam, and as soon as I have time, I'll help to enhance the documentation.

**Comment by jamescgibson** [comment]
@survivant Great to hear. Could you comment on the style of fixup that I've proposed in #185? Would love to have comments before it is merged.
